<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\P3DDebinarizer.csproj" />
    <ProjectReference Include="..\libs\BIS.P3D\BIS.P3D.csproj" />
    <ProjectReference Include="..\libs\BIS.Core\BIS.Core.csproj" />
    <ProjectReference Include="..\libs\BIS.PBO\BIS.PBO.csproj" />
  </ItemGroup>

</Project>
